name: 'AutoMarkdownContents'
description: 'Auto generate markdown contents section'
inputs:
  auto:
    type: boolean
    required: false
    default: false
  file: 
    required: true
    default: "README.md"
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-python@v4
    with:
      python-version: '3.8' 
  - run: pip install git+https://github.com/thatrandomperson5/AutoMarkdownContents
    shell: bash

  - run: python -m AutoContentsGen ${{ inputs.file }} -a
    shell: bash
    if: ${{ inputs.auto != 'false' }}
  - run: python -m AutoContentsGen ${{ inputs.file }}
    shell: bash
    if: ${{ inputs.auto == 'false' }}
      
