on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test the action on the file
    steps:
      - uses: actions/checkout@v3
      - uses: thatrandomperson5/AutoMarkdownContents@0.0.2
        with:
          file: README.md
