on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test the action on the file
    steps:
      - uses: actions/checkout@v3
      - uses: thatrandomperson5/AutoMarkdownContents@v1.0.8
        with:
          file: test.md
          skip-first: true
          exclude: |
             tenent-phrygum-animam-ignorat-humo-versato
             in-igneus-tenuantur-super
            
      - run: cat contents.md
