on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test the action on the file
    steps:
      - uses: actions/checkout@v3
      - uses: thatrandomperson5/AutoMarkdownContents@v1.0.4
        with:
          file: test.md
      - run: cat contents.md
