on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test the action on the file
    steps:
      - uses: actions/checkout@v3
      - uses: thatrandomperson5/AutoMarkdownContents@v1.0.6
        with:
          file: test.md
          skip-first: true
          exclude:
             "Tenent Phrygum animam ignorat humo versato"
            
      - run: cat contents.md
